version: '3.8'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    environment:
      POSTGRES_PASSWORD: cw-pass-local
      POSTGRES_USER: cw
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"