// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://citizenwallet.xyz",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/citizenwallet",
            "email": "support@citizenspring.earth"
        },
        "license": {
            "name": "MIT",
            "url": "https://raw.githubusercontent.com/citizenwallet/indexer/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/logs/transfers/{token_address}/{acc_addr}": {
            "get": {
                "description": "get transfer logs for a given token and account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Fetch transfer logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Contract Address",
                        "name": "token_address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Address of the account",
                        "name": "acc_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Response": {
            "type": "object",
            "properties": {
                "array": {},
                "meta": {},
                "object": {},
                "response_type": {
                    "description": "The response type\nin: body",
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.ResponseType"
                        }
                    ]
                }
            }
        },
        "common.ResponseType": {
            "type": "string",
            "enum": [
                "object",
                "array",
                "secure"
            ],
            "x-enum-varnames": [
                "ResponseTypeObject",
                "ResponseTypeArray",
                "ResponseTypeSecure"
            ]
        }
    },
    "securityDefinitions": {
        "Authorization Bearer": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Citizen Wallet Indexer API",
	Description:      "This is a server which handles token contract indexing, user operations, and other support functions for the app.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
